// Mocks generated by Mockito 5.4.6 from annotations
// in aura/test/features/ai/rag/services/context_builder_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aura/features/ai/embeddings/domain/entities/indexed_document_chunk.dart'
    as _i4;
import 'package:aura/features/ai/embeddings/domain/repositories/embedding_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EmbeddingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmbeddingRepository extends _i1.Mock
    implements _i2.EmbeddingRepository {
  MockEmbeddingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveEmbedding(_i4.IndexedDocumentChunk? embedding) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEmbedding,
          [embedding],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveEmbeddings(List<_i4.IndexedDocumentChunk>? embeddings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEmbeddings,
          [embeddings],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.IndexedDocumentChunk>> getDocumentEmbeddings(
          String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentEmbeddings,
          [documentId],
        ),
        returnValue: _i3.Future<List<_i4.IndexedDocumentChunk>>.value(
            <_i4.IndexedDocumentChunk>[]),
      ) as _i3.Future<List<_i4.IndexedDocumentChunk>>);

  @override
  _i3.Future<void> deleteDocumentEmbeddings(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocumentEmbeddings,
          [documentId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
