// Mocks generated by Mockito 5.4.6 from annotations
// in aura/test/features/ai/rag/services/rag_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:aura/features/ai/rag/domain/entities/ai_config.dart' as _i3;
import 'package:aura/features/ai/rag/domain/entities/ai_stream_event.dart'
    as _i13;
import 'package:aura/features/ai/rag/domain/entities/context_chunk.dart'
    as _i10;
import 'package:aura/features/ai/rag/domain/providers/ai_provider.dart' as _i2;
import 'package:aura/features/ai/rag/domain/providers/ai_provider_factory.dart'
    as _i12;
import 'package:aura/features/ai/rag/domain/services/context_builder_service.dart'
    as _i9;
import 'package:aura/features/ai/rag/domain/services/prompt_builder_service.dart'
    as _i11;
import 'package:aura/features/search/domain/engines/abstract_search_engine.dart'
    as _i4;
import 'package:aura/features/search/domain/entities/search_query.dart' as _i8;
import 'package:aura/features/search/domain/entities/search_result.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAiProvider_0 extends _i1.SmartFake implements _i2.AiProvider {
  _FakeAiProvider_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAiConfig_1 extends _i1.SmartFake implements _i3.AiConfig {
  _FakeAiConfig_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AbstractSearchEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractSearchEngine extends _i1.Mock
    implements _i4.AbstractSearchEngine {
  MockAbstractSearchEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get engineType => (super.noSuchMethod(
        Invocation.getter(#engineType),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#engineType),
        ),
      ) as String);

  @override
  _i6.Future<List<_i7.SearchResult>> search(_i8.SearchQuery? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue:
            _i6.Future<List<_i7.SearchResult>>.value(<_i7.SearchResult>[]),
      ) as _i6.Future<List<_i7.SearchResult>>);
}

/// A class which mocks [ContextBuilderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextBuilderService extends _i1.Mock
    implements _i9.ContextBuilderService {
  MockContextBuilderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i10.ContextChunk>> buildContext(
    List<_i7.SearchResult>? results, {
    int? maxLength = 3000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildContext,
          [results],
          {#maxLength: maxLength},
        ),
        returnValue:
            _i6.Future<List<_i10.ContextChunk>>.value(<_i10.ContextChunk>[]),
      ) as _i6.Future<List<_i10.ContextChunk>>);
}

/// A class which mocks [PromptBuilderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPromptBuilderService extends _i1.Mock
    implements _i11.PromptBuilderService {
  MockPromptBuilderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String buildPrompt(
    String? query,
    List<_i10.ContextChunk>? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildPrompt,
          [
            query,
            context,
          ],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #buildPrompt,
            [
              query,
              context,
            ],
          ),
        ),
      ) as String);

  @override
  String getFallbackMessage() => (super.noSuchMethod(
        Invocation.method(
          #getFallbackMessage,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getFallbackMessage,
            [],
          ),
        ),
      ) as String);
}

/// A class which mocks [AiProviderFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiProviderFactory extends _i1.Mock implements _i12.AiProviderFactory {
  MockAiProviderFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AiProvider createProvider(_i3.AiConfig? config) => (super.noSuchMethod(
        Invocation.method(
          #createProvider,
          [config],
        ),
        returnValue: _FakeAiProvider_0(
          this,
          Invocation.method(
            #createProvider,
            [config],
          ),
        ),
      ) as _i2.AiProvider);
}

/// A class which mocks [AiProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiProvider extends _i1.Mock implements _i2.AiProvider {
  MockAiProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AiConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeAiConfig_1(
          this,
          Invocation.getter(#config),
        ),
      ) as _i3.AiConfig);

  @override
  _i6.Future<String> generateContent(String? prompt) => (super.noSuchMethod(
        Invocation.method(
          #generateContent,
          [prompt],
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateContent,
            [prompt],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Stream<_i13.AiStreamEvent> streamGenerateContent(String? prompt) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamGenerateContent,
          [prompt],
        ),
        returnValue: _i6.Stream<_i13.AiStreamEvent>.empty(),
      ) as _i6.Stream<_i13.AiStreamEvent>);
}
