import 'dart:collection';
import '../../core/constants/app_constants.dart';
import '../models/embedding_result.dart';

/// An LRU cache for embeddings to prevent redundant re-computation of identical text chunks.
class EmbeddingCache {
  final int maxSize;
  final LinkedHashMap<String, EmbeddingResult> _cache = LinkedHashMap<String, EmbeddingResult>();

  EmbeddingCache({this.maxSize = AppConstants.embeddingCacheMaxSize});

  /// Retrieves an embedding from the cache if it exists.
  EmbeddingResult? get(String textHash) {
    if (_cache.containsKey(textHash)) {
      // Move to end (most recently used)
      final result = _cache.remove(textHash)!;
      _cache[textHash] = result;
      return result;
    }
    return null;
  }

  /// Adds an embedding to the cache.
  void put(String textHash, EmbeddingResult result) {
    if (_cache.containsKey(textHash)) {
      _cache.remove(textHash);
    } else if (_cache.length >= maxSize) {
      // Remove oldest (least recently used)
      _cache.remove(_cache.keys.first);
    }
    _cache[textHash] = result;
  }

  /// Invalidates cache entries generated by an older model version.
  void invalidateByModel(String modelVersion) {
    _cache.removeWhere((key, value) => value.modelVersion != modelVersion);
  }

  /// Clears the entire cache.
  void clear() {
    _cache.clear();
  }
}
